### ISSUE TITLE
character repaint problem in readonly mode

### ISSUE THREAD

**Issue by lancos** [Simsys/qhexedit2#81] opened 2017-04-27 14:33 UTC
I have repaint problem in readonly mode, a missing char under the cursor in high address locations.
To reproduce load a file bigger than ten kilobytes (for example qhexedit.o), activate readonly mode, then scroll to some high address locations, and click on the hex charaters, the character under the cursor disappear. Alternatively select more than few bytes, the character after the selection disappear just like the attached snapshot.

![qhexedit_bug](https://cloud.githubusercontent.com/assets/15278592/25488332/0b30e4fa-2b67-11e7-8e45-d67ceb89f02e.png)

**Comment by Simsys** [comment] 2017-05-18 17:49
I can reproduce this behaviour. Please submit a pull request to just fix this bug.

Thanks

**Comment by audetto** [comment] 2017-07-14 20:11
So I create a pull request for this issue.

https://github.com/Simsys/qhexedit2/pull/85

There is one thing I do not understand.
I run this widget in KDE Fedora 25 and the cursor invisible because it is painted in the same background as the rest of the text.

viewport()->palette().color(QPalette::Base)

How is it supposed to work? I normally force a different colour and I can see it perfectly.

Andrea

**Comment by lancos** [comment] 2017-07-14 23:39
Hi, unfortunately your patch doesn't fix the problem, now the digit doesn't disappear, but it is incorrect.
For example this is the file without selections:
![snapshot27](https://user-images.githubusercontent.com/15278592/28234269-15d69fe2-68fe-11e7-9cb8-cde41e36e165.png)

and this is the file with selection, note the byte after the selection, the first digit is duplicated
![snapshot28b](https://user-images.githubusercontent.com/15278592/28234284-4002d894-68fe-11e7-8cdc-766039d7ad67.png)

**Comment by lancos** [comment] 2017-07-14 23:51
This was my patch if you want to compare
[0001-fix-repaint-cursor-in-readonly-mode.txt](https://github.com/Simsys/qhexedit2/files/1149877/0001-fix-repaint-cursor-in-readonly-mode.txt)

**Comment by audetto** [comment] 2017-07-15 05:57
Indeed, thank you for spotting this. It is fixed now.
I had a look at your patch and, I seem to understand that you skip cursor repainting if it is in read only mode.
Because the cursor in invisible anyway, this fixes the visible issues, but if you actually want to see the cursor in read only mode (as I said, paint it yellow for instance), you will have to fix the issues I addressed in the pull request above.

I think a very nice extension would be to paint the cursor in a visible colour and under both panels. A bit like when you select, that you see both selections.

**Comment by audetto** [comment] 2017-07-15 15:50
This is probably a good choice for the read-only cursor background

**Comment by lancos** [comment] 2017-07-19 09:46
Ok, now I understand the logic: blkinking cursor in edit mode and full bounding box rectangle cursor in read-only mode, thank you for your fix. I refined your code to adjust painting when switching from read-only to edit mode and viceversa. Now it seems to work as expected, here the code:

	// paint cursor
	// _cursorPosition counts in 2, _bPosFirst counts in 1
	int hexPositionInShowData = _cursorPosition - 2 * _bPosFirst;
	// due to scrolling the cursor can go out of the currently displayed data
	if ((hexPositionInShowData >= 0) && (hexPositionInShowData < _hexDataShown.size()))
	{
		if (!_readOnly)
		{
			QColor color;

			if (_blink && hasFocus())
			{
				color = viewport()->palette().color(QPalette::WindowText);
			}
			else
			{
				if (_editAreaIsAscii)
					color = _asciiAreaColor;
				else
					color = viewport()->palette().color(QPalette::Base);
			}
			painter.fillRect(_cursorRect, color);
		}
		else
		{
			painter.fillRect(QRect(_pxCursorX - pxOfsX, _pxCursorY - _pxCharHeight + _pxSelectionSub, _pxCharWidth, _pxCharHeight), viewport()->palette().dark().color());
			if (_editAreaIsAscii)
			{
				// every 2 hex there is 1 ascii
				int asciiPositionInShowData = hexPositionInShowData / 2;

				int ch = (uchar)_dataShown.at(asciiPositionInShowData);
				if (ch < ' ')
					ch = '.';

				painter.drawText(_pxCursorX - pxOfsX, _pxCursorY, QChar(ch));
			}
			else
			{
				painter.drawText(_pxCursorX - pxOfsX, _pxCursorY, _hexDataShown.mid(hexPositionInShowData, 1));
			}
		}
	}

**Closed** 2017-11-16 19:34 UTC
Labels: bug
